### ISSUE TITLE
Upgrade to webpack 5?

### ISSUE THREAD

**Issue by cyphercider** [rvagg/polendina#15]
Hey, first off, thanks for the great testing library!

I'm not sure if upgrading to webpack 5 is something you're interested in, but if so, FYI as a datapoint, I got an error similar to [this](https://stackoverflow.com/questions/53227877/progressplugin-typeerror-cannot-read-property-tap-of-undefined) when running tests with polendina because my project is using webpack 5 yet polendina is using webpack 4. 

If you don't plan to upgrade to webpack 5, please feel free to close this issue, thanks!

**Comment by rvagg** [comment]
Yes! I plan to upgrade, everything's been building up to 5 and we've just been waiting for it to land. The challenge is in doing the compatibility work which I haven't got to yet. The goal of Polendina is to test in the most common browser publishing environment and I'm guessing that WebPack 5 will be that environment so it needs to happen.

**Comment by jeffkhull** [comment]
I will say that upgrading to webpack 5 was kind of a pain, because they decided to take away all the node polyfills.  So you have to add them yourself.  I got it figured out in my project with some moderate frustration - I'm not sure what it would take for Polendina.  I tried briefly to clone Polendina locally and give the refactor to v5 a whack, but I don't understand enough of what's going on in Polendina to do it (at least not quickly).

Just FYI in case it's helpful, I had to add this:

```js
  resolve: {
    fallback: {
      buffer: require.resolve('buffer/'),
      util: require.resolve('util/'),
    },
  }
```

And this: 
```js
  plugins: [
    new webpack.ProvidePlugin({
      Buffer: ['buffer', 'Buffer'],
    }),
  ],
```
And also I had to install the `buffer` and `util` packages from npm.

For now I've downgraded back to Webpack 4 (I get no real benefit from webpack 5) since I need to use Polendina in my project.

Cheers!
